[build-system]
build-backend = "hatchling.build"
requires = [ "hatch-docstring-description", "hatch-vcs", "hatchling" ]

[project]
name = "fast-array-utils"
readme = "README.rst"
license = "MPL-2.0"
authors = [
  { name = "Philipp A.", email = "flying-sheep@web.de" },
]
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: R",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
]
dynamic = [ "description", "version" ]
dependencies = ["numba", "numpy"]

optional-dependencies.dev = [ "pre-commit", "setuptools-scm" ]
optional-dependencies.doc = [
  "lxml",                       # For scraping the R link info
  "scanpydoc[theme,typehints]",
  "sphinx>=3",
]
optional-dependencies.test = [
  "pygments",
  "pytest",
  "pytest-faulthandler",
  "scanpy",
]
urls.'Documentation' = "https://icb-anndata2ri.readthedocs-hosted.com/"
urls.'Issue Tracker' = "https://github.com/theislab/anndata2ri/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc"
urls.'Source Code' = "https://github.com/theislab/anndata2ri"

[tool.hatch.version]
source = "vcs"
raw-options = { local_scheme = "no-local-version" } # be able to publish dev version

[tool.hatch.envs.default]
installer = "uv"

[tool.hatch.envs.docs]
features = [ "doc" ]
[tool.hatch.envs.docs.scripts]
build = "sphinx-build -M html docs docs/_build"

[tool.hatch.envs.hatch-test]
features = [ "test" ]
extra-dependencies = [ "ipykernel" ]

[tool.ruff]
line-length = 100
lint.select = [ "ALL" ]
lint.ignore = [
  "C408",    # dict() calls are nice
  "COM812",  # trailing commas handled by black
  "D203",    # prefer 0 to 1 blank line before class members
  "D213",    # prefer docstring summary on first line
  "FIX002",  # “TODO” comments
  "PLR0913", # having many (kw)args is fine
  "Q",       # handled by formatter
  "S101",    # asserts are fine
]
lint.per-file-ignores."docs/**/*.py" = [ "INP001" ] # No __init__.py in docs
lint.per-file-ignores."tests/**/test_*.py" = [
  "D100",    # tests need no module docstrings
  "D103",    # tests need no function docstrings
  "INP001",  # tests should not have __init__.py
  "PLR2004", # tests use magic values
  "S101",    # tests use `assert`
]
lint.allowed-confusables = [ "×", "’" ]
lint.flake8-copyright.notice-rgx = "SPDX-License-Identifier: MPL-2\\.0"
lint.isort.known-first-party = [ "fast_array_utils" ]
lint.isort.lines-after-imports = 2
lint.isort.required-imports = [ "from __future__ import annotations" ]

[tool.pytest.ini_options]
addopts = [
  "--import-mode=importlib",
  "-Werror",
  "--strict-markers",
]

[tool.mypy]
strict = true
explicit_package_bases = true
mypy_path = "src"
